repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check app
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy app
        language: system
        pass_filenames: false
      - id: import-linter
        name: import-linter
        entry: lint-imports
        language: system
        pass_filenames: false
