<?xml version="1.0" encoding="UTF-8"?>
<!-- April 22, 2021 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:gm2mecho_s1="http://www.telefonica.com/wsdl/UNICA/SOAP/Globalm2m/echo/v1/services"
    xmlns:gm2mecho_s1t="http://www.telefonica.com/schemas/UNICA/SOAP/Globalm2m/echo/v1/types"
    xmlns:ucf="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v1/faults"
    targetNamespace="http://www.telefonica.com/wsdl/UNICA/SOAP/Globalm2m/echo/v1/services">

    <wsdl:import
        namespace="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v1/faults"
        location="UNICA_API_SOAP_common_faults_v1_1.wsdl" />

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
            <xsd:import
                namespace="http://www.telefonica.com/schemas/UNICA/SOAP/Globalm2m/echo/v1/types"
                schemaLocation="UNICA_API_SOAP_Globalm2m_echo_types_v1_0.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="EchoRequest">
        <wsdl:part name="parameters" element="gm2mecho_s1t:echo"/>
    </wsdl:message>
    <wsdl:message name="EchoResponse">
        <wsdl:part name="parameters"
            element="gm2mecho_s1t:echoResponse" />
    </wsdl:message>
    
    <wsdl:portType name="GlobalM2MEchoPort">
        <wsdl:operation name="echo">
            <wsdl:input message="gm2mecho_s1:EchoRequest" />
            <wsdl:output message="gm2mecho_s1:EchoResponse" />
            <wsdl:fault name="ClientException" message="ucf:ClientException" />
            <wsdl:fault name="ServerException" message="ucf:ServerException" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="GlobalM2MEchoSOAPBinding"
        type="gm2mecho_s1:GlobalM2MEchoPort">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="echo">
            <soap:operation soapAction="urn:echo" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="ClientException">
                <soap:fault name="ClientException" use="literal" />
            </wsdl:fault>
            <wsdl:fault name="ServerException">
                <soap:fault name="ServerException" use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="GlobalM2MEchoService">
        <wsdl:port name="GlobalM2MEcho"
            binding="gm2mecho_s1:GlobalM2MEchoSOAPBinding">
            <soap:address
                location="https://kiteplatform-api.telefonica.com:8010/services/SOAP/GlobalM2M/Echo/v1/r12" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
